---

copy_pub_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

timezone:
  - America/Chicago

#allowed_ssh_networks:
#  - 192.168.122.0/24
#  - 10.10.10.0/24

unnecessary_services:
  - postfix
  - ypserv
  - rsh-server
  - vsftpd*
  - telnet-server
  - tftp-server

unnecessary_software:
  - postfix

port_list:
  - { port: 8967/tcp, state: enabled }

dnf_packages:

  - git
  - dnf-plugins-core
  - net-tools
  - curl
  - ipcalc
  - vim-common
  - vim-enhanced
  - vim-filesystem
  - vim-minimal
  - vim-X11
  - nano
  - tmux
  - zsh
  - flatpak
  - flatpak-selinux
  - flatpak-xdg-utils
  - libvirt
  - libvirt-daemon
  - libvirt-daemon-config-network
  - libvirt-daemon-config-nwfilter
  - libvirt-client
  - libvirt-daemon-driver-interface
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nodedev
  - libvirt-daemon-driver-nwfilter
  - python3-libvirt
  - pcp-pmda-libvirt
  - fence-virtd-libvirt
  - libvirt-nss
  - libvirt-libs
  - libvirt-glib
  - libvirt-dbus
  - libvirt-daemon-kvm
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-driver-storage-rbd
  - libvirt-daemon-driver-storage-mpath
  - libvirt-daemon-driver-storage-logical
  - libvirt-daemon-driver-storage-iscsi
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-qemu
  - ipxe-roms-qemu
  - qemu-ga-win
  - qemu-guest-agent
  - qemu-img
  - qemu-kvm
  - qemu-kvm-audio-pa
  - qemu-kvm-block-curl
  - qemu-kvm-block-rbd
  - qemu-kvm-common
  - qemu-kvm-core
  - qemu-kvm-device-display-virtio-gpu
  - qemu-kvm-device-display-virtio-gpu-pci
  - qemu-kvm-device-display-virtio-vga
  - qemu-kvm-device-usb-host
  - qemu-kvm-device-usb-redirect
  - qemu-kvm-docs
  - qemu-kvm-tools
  - qemu-kvm-ui-egl-headless
  - qemu-kvm-ui-opengl
  - qemu-pr-helper
  - iperf3
  - chrome-gnome-shell
  - gnome-autoar
  - gnome-backgrounds
  - gnome-backgrounds-extras
  - gnome-bluetooth
  - gnome-bluetooth-libs
  - gnome-calculator
  - gnome-characters
  - gnome-classic-session
  - gnome-color-manager
  - gnome-common
  - gnome-connections
  - gnome-control-center
  - gnome-control-center-filesystem
  - gnome-desktop3
  - gnome-desktop3-devel
  - gnome-devel-docs
  - gnome-disk-utility
  - gnome-extensions-app
  - gnome-font-viewer
  - gnome-initial-setup
  - gnome-keyring
  - gnome-keyring-pam
  - gnome-kiosk
  - gnome-kiosk-script-session
  - gnome-kiosk-search-appliance
  - gnome-logs
  - gnome-menus
  - gnome-online-accounts
  - gnome-online-accounts-devel
  - gnome-photos
  - gnome-photos-tests
  - gnome-remote-desktop
  - gnome-screenshot
  - gnome-session
  - gnome-session-wayland-session
  - gnome-session-xsession
  - gnome-settings-daemon
  - gnome-shell
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-classification-banner
  - gnome-shell-extension-common
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-desktop-icons
  - gnome-shell-extension-drive-menu
  - gnome-shell-extension-gesture-inhibitor
  - gnome-shell-extension-heads-up-display
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-native-window-placement
  - gnome-shell-extension-panel-favorites
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-screenshot-window-sizer
  - gnome-shell-extension-systemMonitor
  - gnome-shell-extension-top-icons
  - gnome-shell-extension-updates-dialog
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-window-list
  - gnome-shell-extension-windowsNavigator
  - gnome-shell-extension-workspace-indicator
  - gnome-software
  - gnome-system-monitor
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-themes-extra
  - gnome-tour
  - gnome-tweaks
  - gnome-user-docs
  - gnome-video-effects
  - libgnomekbd
  - libproxy-gnome
  - NetworkManager-libreswan-gnome
  - pinentry-gnome3
  - qgnomeplatform
  - subversion-gnome
  - xdg-desktop-portal-gnome
  - cargo
  - cargo-doc
  - golang
  - golang-bin
  - golang-docs
  - golang-misc
  - golang-src
  - golang-tests
  - iotop
  - libnfsidmap
  - nfs-utils
  - nfs4-acl-tools
  - sssd-nfs-idmap
  - libstoragemgmt-nfs-plugin
  - nfs-utils-coreos
  - nfsv4-client-utils
  - pcp-pmda-nfsclient
  - texlive-mfnfss
  - texlive-psnfss
  - libselinux-ruby
  - ruby
  - ruby-default-gems
  - ruby-devel
  - ruby-libs
  - rubygem-bigdecimal
  - rubygem-bundler
  - rubygem-io-console
  - rubygem-irb
  - rubygem-json
  - rubygem-minitest
  - rubygem-mysql2
  - rubygem-pg
  - rubygem-power_assert
  - rubygem-psych
  - rubygem-rake
  - rubygem-rbs
  - rubygem-rdoc
  - rubygem-rexml
  - rubygem-rss
  - rubygem-test-unit
  - rubygem-typeprof
  - rubygems
  - rubygems-devel
  - avahi
  - avahi-libs
  - avahi-glib
  - ansible-collection-microsoft-sql
  - ansible-collection-redhat-rhel_mgmt
  - ansible-core
  - ansible-freeipa
  - ansible-freeipa-tests
  - ansible-pcp
  - ansible-test
