#[edgeos:vars]
#ansible_connection=ansible.netcommon.network_cli
#ansible_network_os=community.network.edgeos

[vyos]
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: vyos.vyos.vyos
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q bastion01"'

#[persistent_connection]
#ssh_type = libssh
#ansible_become=yes
#ansible_become_method=enable
