---
collections:
  - name: community.network
    version: ">=5.0.0,<6.0.0"
  - name: community.general
    version: ">=9.0.0,<10.0.0"
  - name: community.routeros
    version: ">=2.12.0,<3.0.0"
  - name: vyos.vyos
    version: ">=4.2.0,<5.0.0"
  - name: community.libvirt
    version: ">=1.3.0,<2.0.0"
  - name: ansible.posix
    version: ">=1.5.4,<2.0.0"
