---
collections:
  - name: community.network
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.routeros
    source: https://galaxy.ansible.com
  - name: community.vyos
    source: https://galaxy.ansible.com
  - name: community.libvirt
    source: https://galaxy.ansible.com