---
- name: Converge ctrld
  hosts: all
  become: true
  vars_files:
    - group_vars/ctrld.yml
  vars:
    resolver_id: "{{ resolver_id | default('test-resolver-id') }}"
    primary_upstream: "https://dns.google/dns-query"
    listener_ip: "0.0.0.0"
    listener_port: "{{ (ansible_distribution | lower) == 'ubuntu' | ternary(5355, 5354) }}"
    ctrld_manage_service: false
  tasks:
    - name: Include ctrld role tasks
      import_tasks: roles/ctrld/tasks/main.yml
