---
driver:
  name: docker
platforms:
  - name: debian-bookworm
    image: debian:12
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
  - name: ubuntu-jammy
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
  - name: rockylinux-9
    image: rockylinux:9
    command: /usr/lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: testinfra
