---
driver:
  name: docker
platforms:
  - name: debian-bookworm
    image: debian:12
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - 127.0.0.1:5354:5354
  - name: ubuntu-jammy
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - 127.0.0.1:5355:5355
  - name: rockylinux-9
    image: rockylinux:9
    command: /usr/lib/systemd/systemd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
verifier:
  name: testinfra
