---
  - name: Download ctrld installer script
    get_url:
      url: https://api.controld.dev/dl
      dest: /usr/local/bin/ctrld_installer.sh
      mode: '0755'
  - name: Install ctrld
    command: /usr/local/bin/ctrld_installer.sh {{ resolver_id }} forced
    args:
      creates: /usr/local/bin/ctrld
  
  - name: Create ctrld configuration
    template:
      src: roles/ctrld/templates/ctrld.toml.j2
      dest: /etc/controld/ctrld.toml
    notify:
      - restart ctrld
  
  - name: Ensure ctrld service started
    ansible.builtin.service:
      name: ctrld
      state: started
  
  - name: Enable ctrld service
    ansible.builtin.service:
      name: ctrld
      enabled: yes
