---
  - name: Download and install ctrld
    shell: |
      sudo sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s "{{ resolver_id }}"'
    args:
      executable: /bin/bash
  
  - name: Create ctrld configuration
    template:
      src: ctrld.toml.j2
      dest: /etc/controld/ctrld.toml
    notify:
      - restart ctrld
  
  - name: Enable and start systemd service
    ansible.builtin.service:
      name: ctrld
      enabled: yes
      state: started
