---
  - name: Download and install ctrld
    shell: >
      sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s {{ provisioning_code }}'
    args:
      executable: /bin/bash
  - name: Enable and start systemd service
    ansible.builtin.service:
      name: ctrld
      enabled: yes
      state: started
