---
- name: Upgrade and Reboot RHEL & Debian family Linux distros
  become: true
  hosts: all
  vars_files:
    - ../group_vars/rhel.yml
  tasks:
    - name: Copy Dotfiles
      copy:
        dest: /home/{{ ansible_user }}/
        src: ../roles/common/files/home/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      tags:
        - dots