---
- name: EdgeOS Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: "Gather Facts"
      vyos.vyos.vyos_facts:
        gather_subset: min
        gather_network_resources: interfaces

    - name: "Show ethX interfaces"
      vyos.vyos.vyos_command:
        commands:
          - "show interfaces ethernet {{ item }}"
      loop:
        - eth0
        - eth1
        - eth2
        - eth3
        - eth4
        - eth5
        - eth6
        - switch0
        - lo

    - name: "Print Information"
      ansible.builtin.debug:
        var: result
        verbosity: 2

    - debug:
        msg: "{{ ansible_facts }}"
