---
- name: Copy and install rpms
  hosts: all
  become: true

  vars:
    rpm:
      - bat.rpm

  tasks:

    - name: "Transfer Files"
      ansible.builtin.copy:
        src: "../roles/rhel/files/rpms/{{ item }}"
        dest: /home/rexuser/
#        mode: preserve
      loop: "{{ rpm }}"
      register: copied

    - name: "Install RPMs from local copied files"
      ansible.builtin.dnf:
        state: present
        disable_gpg_check: true
        name: "{{ copied.results | map(attribute='dest') | list }}"
