---
- name: Copy and install rpms
  hosts: all
  become: true

  vars:
    rpm:
      - bat.rpm

  tasks:

    - name: "Transfer Files"
      ansible.builtin.fetch.copy:
        src: "../roles/rhel/files/rpms/{{ item }}"
        dest: /home/rexuser/
#        mode: preserve
      loop: "{{ rpm }}"
      register: copied

    - name: "Install RPMs from local copied files"
      ansible.builtin.dnf:
        name: "/home/azazel/{{ rpm }}"
        state: present
        name: "{{ copied | json_query('results[?!failed].dest[]') }}"
